# Use this command and change the user and password:
# echo $(htpasswd -nb <user> <password>)


[http.middlewares]
  [http.middlewares.basic-auth.basicAuth]
    users = [
      "<enter-output-from-command-above-here>",
    ]
